title: UBC MATH 316 Partial Differential Equations
author: UBC Math
copyright: "2024"
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
only_build_toc_files: true
html:
  home_page_in_navbar: false
  use_repository_button: true
launch_buttons:
  jupyterhub_url: https://ubc.syzygy.ca/jupyter
  notebook_interface: "jupyterlab"
repository:
  url: https://github.com/UBCMath/MATH316
  branch: main

# ghp-import -n -p -f _build/html