title: MATH 316
author: UBC Math
# logo: img/nn.png
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  extra_extensions:
    - sphinx_proof
only_build_toc_files: true
execute:
    execute_notebooks: cache
html:
  home_page_in_navbar: false
  use_repository_button: true
launch_buttons:
  jupyterhub_url: https://ubc.syzygy.ca/jupyter
  notebook_interface: "jupyterlab"
repository:
  url: https://github.com/UBCMath/math316
  branch: main

# ghp-import -n -p -f _build/html